RubikStore/RubikStore/Models/Giohang.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RubikStore.Models
{
    public class Giohang
    {
        dbRubikStoreDataContext data = new dbRubikStoreDataContext();
        public int id { get; set; }
        [Display(Name ="Tên")]
        public string ten { get; set; }
        [Display(Name = "Ảnh bìa")]
        public string hinh { get; set; }
        [Display(Name = "Giá bán")]
        public Double gia { get; set; }
        [Display(Name = "Số lượng")]
        public int iSoLuong { get; set; }
        [Display(Name = "Thành tiền")]
        public Double dThanhTien
        {
            get { return iSoLuong * gia; }
        }
        public Giohang(int id)
        {
            this.id = id;
            Rubik rubik = data.Rubiks.Single(n => n.id == id);
            ten = rubik.ten;
            hinh = rubik.hinh;
            gia = double.Parse(rubik.gia.ToString());
            iSoLuong = 1;
        }
    }
}

RubikStore/RubikStore/Controllers/GIoHangController.cs
using RubikStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RubikStore.Controllers
{
    public class GIoHangController : Controller
    {
        // GET: GIoHang
        dbRubikStoreDataContext data = new dbRubikStoreDataContext();
        public List<Giohang>    Laygiohang()
        {
            List<Giohang> lstGioHang = Session["Giohang"] as List<Giohang>;
            if (lstGioHang == null)
            {
                lstGioHang = new List<Giohang>();
                Session["GioHang"] = lstGioHang;
            }
            return lstGioHang;
        }

        public ActionResult ThemGioHang(int id, string strURL)
        {
            List<Giohang> lstGioHang = Laygiohang();
            Giohang sanpham = lstGioHang.Find(n => n.id == id);
            if (sanpham == null)
            {
                sanpham = new Giohang(id);
                lstGioHang.Add(sanpham);
                return Redirect(strURL);
            }
            else
            {
                sanpham.iSoLuong++;
                return Redirect(strURL);
            }
        }

        private  int TongSoLuong()
        {
            int tsl = 0;
            List<Giohang> lstGioHang = Session["GioHang"] as List<Giohang>;
            if (lstGioHang != null)
            {
                tsl = lstGioHang.Sum(n => n.iSoLuong);
            }
            return tsl;
        }

        private int TongSoLuongSanPham()
        {
            int tsl = 0;
            List<Giohang> lstGioHang = Session["GioHang"] as List<Giohang>;
            if (lstGioHang != null)
            {
                tsl = lstGioHang.Count;
            }
            return tsl;
        }
       
        private double TongTien()
        {
            double tt = 0;
            List<Giohang> lstGioHang = Session["GioHang"] as List<Giohang>;
            if (lstGioHang != null)
            {
                tt = lstGioHang.Sum(n => n.dThanhTien);
            }
            return tt;
        }

        public ActionResult GioHang()
        {
            List<Giohang> lstGioHang = Laygiohang();
            ViewBag.Tongsoluonng = TongSoLuong();
            ViewBag.TongTien = TongTien();
            ViewBag.Tongsoluongsanpham = TongSoLuongSanPham();
            return View(lstGioHang);
        }

        public ActionResult GioHangPartial()
        {
            ViewBag.Tongsoluonng = TongSoLuong();
            ViewBag.TongTien = TongTien();
            ViewBag.Tongsoluongsanpham = TongSoLuongSanPham();
            return PartialView();
        }

        public ActionResult XoaGioHang(int id)
        {
            List<Giohang> lstGioHang = Laygiohang();
            Giohang sanpham = lstGioHang.SingleOrDefault(n => n.id == id);
            if (sanpham != null)
            {
                lstGioHang.RemoveAll(n => n.id == id);
                return RedirectToAction("GioHang");
            }
            return RedirectToAction("GioHang");
        }

        public ActionResult CapnhatGioHang(int id, FormCollection collection)
        {
            List<Giohang> lstGioHang = Laygiohang();
            Giohang sanpham = lstGioHang.SingleOrDefault(n => n.id == id);
            if (sanpham != null)
            {
                sanpham.iSoLuong = int.Parse(collection["txtLog"].ToString());
            }
            return RedirectToAction("GioHang");
        }

        public ActionResult XoaTatCaGioHang()
        {
            List<Giohang> lstGioHang = Laygiohang();
            lstGioHang.Clear();
            return RedirectToAction("GioHang");
        }
    }
}

RubikStore/RubikStore/Controllers/RubikController.cs
using RubikStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RubikStore.Controllers
{
    public class RubikController : Controller
    {
        // GET: Rubik
        dbRubikStoreDataContext data = new dbRubikStoreDataContext();
        public ActionResult Index()
        {
            var all_rubik = from s in data.Rubiks select s;
            return View(all_rubik);
        }
    }
}

RubikStore/RubikStore/Views/GIoHang/GioHang.cshtml
@model IEnumerable<RubikStore.Models.Giohang>

@{
    ViewBag.Title = "GioHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Giỏ hàng</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>

        <th>    @Html.DisplayNameFor(model => model.ten)            </th>
        <th>    @Html.DisplayNameFor(model => model.hinh)           </th>
        <th>    @Html.DisplayNameFor(model => model.gia)            </th>
        <th>    @Html.DisplayNameFor(model => model.iSoLuong)       </th>
        <th>    @Html.DisplayNameFor(model => model.dThanhTien)     </th>

        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>@Html.DisplayFor(modelItem => item.ten)</td>
        <td> <img src="@item.hinh" width="180" /> </td>
        @using (Html.BeginForm("CapnhatGioHang", "GioHang", new { @id = item.id }))
        {
                    <td> @String.Format("{0:0,0}", item.gia) VNĐ</td>
                    <td> <input type="number" min="1" name="txtLog" value="@item.iSoLuong" /></td>
                    <td>@Html.DisplayFor(modelItem => item.dThanhTien)</td>
                    <td>
                        <a href="@Url.Action("Detail", "Rubik", new { id = item.id })"> Chi tiết</a> | @Html.ActionLink("Xoá", "XoaGioHang", new { @id = item.id })
                    </td>
                    <td>
                        <input type="submit" value="Cập nhật" class="btn btn-success" />
                    </td>
        }
    </tr>
}

<tr style="font-weight:bold; text-align:left; color:red">
    <td colspan="2"> Số loại rubik: @ViewBag.Tongsoluongsanpham </td>
    <td colspan="2"> Số lượng rubik: @ViewBag.Tongsoluong   </td>
    <td colspan="2"> Tổng tiền: @String.Format("0:0;0",@ViewBag.Tongtien) VNĐ </td>
</tr>        

<tr style="font-weight:bold; text-align:right; color:blue">
    <td colspan="5">    @Html.ActionLink("Đặt hàng", "Dathang", "GioHang")  </td>
</tr>
</table>

RubikStore/RubikStore/Views/GIoHang/GioHangPartial.cshtml
<a class="getstarted scrollto active" href="@Url.Action("GioHang",
"GioHang")" style="font-weight:bold; text-decoration:none">
    Giỏ hàng (@ViewBag.Tongsoluongsanpham)
</a>